# Generated by Django 4.0.5 on 2022-11-13 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donsnature',
            name='Etat',
        ),
        migrations.RemoveField(
            model_name='donsnature',
            name='categorieObjet',
        ),
        migrations.RemoveField(
            model_name='donsnature',
            name='create',
        ),
        migrations.RemoveField(
            model_name='donsnature',
            name='idTransaction',
        ),
        migrations.RemoveField(
            model_name='donsnature',
            name='typeDons',
        ),
        migrations.RemoveField(
            model_name='donsnature',
            name='typeObjet',
        ),
        migrations.RemoveField(
            model_name='donsnature',
            name='typePersonne',
        ),
    ]
