# Generated by Django 4.0.5 on 2022-09-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant_r',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='enfant_r',
            name='id',
        ),
        migrations.RemoveField(
            model_name='enfant_r',
            name='prenom',
        ),
        migrations.AddField(
            model_name='enfant_r',
            name='newuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
