# Generated by Django 4.0.5 on 2022-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfant_r',
            old_name='annee_naissance',
            new_name='annee_nais',
        ),
        migrations.RenameField(
            model_name='enfant_r',
            old_name='battue',
            new_name='battu',
        ),
        migrations.AddField(
            model_name='enfant_r',
            name='lieu_nais',
            field=models.CharField(default='grand_bassm', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant_r',
            name='tutrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enfant_r',
            name='handicap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='enfant_r',
            name='sexes',
            field=models.CharField(max_length=30),
        ),
    ]
