# Generated by Django 4.0.5 on 2022-11-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_donsnature_etat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donsargent',
            name='iddons',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
