# Generated by Django 4.0.5 on 2022-11-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_annee_naissance_enfant_r_annee_nais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfant_r',
            name='nom',
        ),
    ]
