# Generated by Django 4.0.5 on 2022-11-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_enfant_r_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfant_r',
            old_name='sexes',
            new_name='sexe',
        ),
    ]
