# Generated by Django 4.0.5 on 2022-08-23 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_chef_menage_individu_chef_menage_menage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant_R',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('niveau_etude', models.CharField(blank=True, default='master', max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('handicap', models.CharField(choices=[('S', 'Sans_Handicap'), ('Nv', 'Non_voyant'), ('So', 'Sourd'), ('Mu', 'Muet'), ('Be', 'Begue'), ('Al', 'Albinos'), ('Hms', 'Handicap_membre_superieurs'), ('Hmi', 'Handicap_membre_inferieurs'), ('Hp', 'Handicap_physiques'), ('Au', 'Autre_handicap')], max_length=100)),
                ('battue', models.BooleanField(default=False)),
                ('tuteur', models.BooleanField(default=False)),
                ('pere', models.BooleanField(default=False)),
                ('mere', models.BooleanField(default=False)),
                ('scolariser', models.BooleanField(default=False)),
                ('owner9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfantr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
