# Generated by Django 4.0.5 on 2022-08-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_enfant_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfant_r',
            name='commune',
            field=models.CharField(default='Abidjan', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant_r',
            name='quartier',
            field=models.CharField(default='caloa', max_length=100),
            preserve_default=False,
        ),
    ]
