# Generated by Django 4.0.5 on 2022-08-23 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_enfant_r_commune_enfant_r_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfant_r',
            name='owner9',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfant_rue', to=settings.AUTH_USER_MODEL),
        ),
    ]
