# Generated by Django 4.0.5 on 2022-09-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_enfant_r_owner9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodite',
            name='nature_mur',
        ),
        migrations.RemoveField(
            model_name='commodite',
            name='nature_sol',
        ),
        migrations.RemoveField(
            model_name='commodite',
            name='nature_toit',
        ),
        migrations.AddField(
            model_name='charge',
            name='maladie',
            field=models.CharField(default='palu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conjoint',
            name='maladie',
            field=models.CharField(default='palu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant',
            name='maladie',
            field=models.CharField(default='palu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant_r',
            name='maladie',
            field=models.CharField(default='palu', max_length=100),
            preserve_default=False,
        ),
    ]
