# Generated by Django 4.1.4 on 2024-04-20 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 8, 25, 7, 5879, tzinfo=datetime.timezone.utc), verbose_name='last_login'),
        ),
    ]
