# Generated by Django 4.0.5 on 2022-10-20 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 11, 34, 11, 811202, tzinfo=utc), verbose_name='last_login'),
        ),
    ]
