# Generated by Django 4.0.5 on 2022-11-13 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_alter_newuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 11, 50, 15, 481411, tzinfo=utc), verbose_name='last_login'),
        ),
    ]
