# Generated by Django 4.0.5 on 2022-09-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0002_alter_newuser_is_active_alter_newuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='commune',
        ),
    ]
