# Generated by Django 4.0.5 on 2022-08-20 11:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0003_critere'),
    ]

    operations = [
        migrations.CreateModel(
            name='CritereCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('niveauEtude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('maladie', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('handicap', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('occupations', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexeChef', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('agechef', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('nationalite', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('niveauEtude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('maladie', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('handicap', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('occupations', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereCommodite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eclairage', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('cuisson', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('aeaux', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('ordure', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('nombrep', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('aisance', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('loyer', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('typelogement', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereConj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('niveauEtude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('maladie', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('handicap', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('occupations', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereEnfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agec', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('niveauEtude', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('maladie', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('handicap', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyend', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('equipee', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('equipepo', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditionvie', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('conditionphy', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('conditionoccup', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('conditionnivee', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('quartier', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='CritereMenage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenneage', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('niveauEtudeM', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('typeMenage', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('occupations', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Critere',
        ),
    ]
