# Generated by Django 4.0.5 on 2022-09-12 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0003_remove_affectation_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 8, 16, 10, 475766, tzinfo=utc), verbose_name='last_login'),
        ),
    ]
