# Generated by Django 4.0.5 on 2022-08-31 14:33

import custumer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0005_quartier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=custumer.models.NewUser.nameFile),
        ),
    ]
