# Generated by Django 4.0.5 on 2022-09-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0006_alter_newuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='responsable',
            field=models.CharField(default='issa', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
