# Generated by Django 4.0.5 on 2022-09-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0007_newuser_responsable_alter_newuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='responsable',
            field=models.CharField(default='issa', max_length=30),
        ),
    ]
